### ISSUE TITLE
The spec does test for validations

### ISSUE THREAD

**Issue by tsiege** [learn-co-curriculum/rails-amusement-park-old#1]
Molly noticed the valid tests for all models do not actually test to if the model created meets any sort of validation.  There is also confusion between tests with some models being created for testing other models that aren't valid themselves ( i.e. users created to test attractions).

**Comment by kthffmn** [comment]
Added note (in bold!) about how validations are not part of this lab to the readme.

**Comment by tsiege** [comment]
Haha, noted!
