### ISSUE TITLE
Tests seem to conflict

### ISSUE THREAD

**Issue by corya0687** [learn-co-curriculum/rails-amusement-park-old#19]
Some of the test try to create new users that other tests request a password for? Or maybe i'm just confused?

**Comment by aturkewi** [comment]
@corya0687 Could you add specific examples of the tests that conflict?

**Comment by pletcher** [comment]
Fixed with https://github.com/learn-co-curriculum/rails-amusement-park/pull/22 and https://github.com/learn-co-curriculum/rails-amusement-park/pull/21
