### ISSUE TITLE
Conflicting test (login_helper.rb vs user_features_spec.rb)

### ISSUE THREAD

**Issue by curiositypaths** [learn-co-curriculum/rails-amusement-park-old#32]
**There are two tests which check for the presence of a sign-up link but they have conflicting casing requirements "Sign up" vs "Sign Up".**

**Test #1 in login_helper.rb**
def visit_signup
    visit '/'
    click_link(**'Sign up'**)
  end

**Test #2 in user_features_spec.rb**
 it 'prevents user from viewing user show page and redirects to home page if not logged in' do
    @mindy = User.create(
      name: "Mindy",
      password: "password",
      happiness: 3,
      nausea: 2,
      tickets: 10,
      height: 50
    )
    visit '/users/1'
    expect(current_path).to eq('/')
    expect(page).to have_content("**Sign Up**")
  end

**Comment by gj** [comment]
Hi @curiositypaths !

Thanks for catching this. Fixed in 968ae547338568e07126c7b118a47b5061c24d89
