### ISSUE TITLE
Capybara case sensitivity failure

### ISSUE THREAD

**Issue by clintonn** [learn-co-curriculum/rails-amusement-park-old#33]
Features spec looks for a sign up link on the root url ("/") and expects sign up text to be "Sign Up". Login helper expects to find "Sign up" lowercase u on root url. Fix so that it's consistent.

```ruby
# user_features_spec.rb lines 51-52
    expect(current_path).to eq('/')
    expect(page).to have_content("Sign Up")
```

```ruby
# login_helper.rb lines 4-5
    visit '/'
    click_link('Sign up')
```

**Comment by gj** [comment]
Hi @clintonn !

Thanks for catching this. Fixed in 968ae547338568e07126c7b118a47b5061c24d89
