### ISSUE TITLE
Typo in message when the user does not have enough tickets

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/rails-amusement-park-old#35]
The spec and solution have a typo in the message shown to the user when the user lacks enough tickets. See, e.g., https://github.com/jonbf/rails-amusement-park-v-000/blob/solution/app/models/ride.rb line 42

**Comment by gj** [comment]
Hi @jonbf !

Thanks for catching this. Fixed in 968ae547338568e07126c7b118a47b5061c24d89
