### ISSUE TITLE
Missing design cues

### ISSUE THREAD

**Issue by jcpny1** [learn-co-curriculum/rails-amusement-park-old#37]
The migrations are empty. The README says this is a test-driven lab. The first test is trying to visit a root path. Not a good way to design an app. (Update: it seems that the features tests are running before the models tests.)

**Comment by itzsaga** [comment]
@jcpny1 tests will run in alphabetical order

**Comment by gj** [comment]
Hi @jcpny1 !

There's a note in the README that suggests "check[ing] out the model tests and get[ting] those to pass before moving onto the feature specs." To just run the model tests, you can execute `rspec spec/models/` (or `rspec spec/models/user_spec.rb` for a really fine-grained approach).
