### ISSUE TITLE
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.0/lib/rails/commands/console.rb:29:in `block in parse_arguments': invalid o ption: -b (OptionParser::InvalidOption)

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/rails-amusement-park-old#39]
rails console is not working

**Comment by cjbrock** [comment]
This version of the lab is no longer used. Please see the updated version of the lab here: https://github.com/learn-co-curriculum/rails-amusement-park/
