### ISSUE TITLE
rails console command failure

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/rails-amusement-park-old#40]
unable to start subject command due to following error
// ♥ rails c
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.0/lib/rails/commands/console.rb:29:in `block in parse_arguments': invalid option: -b (OptionParser::InvalidO
ption)

**Comment by cjbrock** [comment]
This version of the lab is no longer used. Please see the updated version of the lab here: https://github.com/learn-co-curriculum/rails-amusement-park/
