### ISSUE TITLE
Lab doesn't do actual auth

### ISSUE THREAD

**Issue by octosteve** [learn-co-curriculum/rails-amusement-park-old#5]
https://github.com/learn-co-curriculum/rails-amusement-park/blob/master/spec/support/login_helper.rb#L54

This lab is used as a "Bringing it all together" lab for authentication. Students should be challenged to use bcrypt, has_secure_password, and create a proper user account. @AnnJohn What do you think?

**Comment by AnnJohn** [comment]
Going to pass this question on to @pletcher. What do you think Chuck?

**Comment by pletcher** [comment]
I agree, @StevenNunez -- how much work do you think it'd be to do real auth in this lab?

**Comment by octosteve** [comment]
@pletcher I think getting them to register and log in with a password that's hashed with bcrypt would be great. We can have ensure they have `current_user` and `logged_in?` helpers too.

**Comment by pletcher** [comment]
I pushed a few fixes -- I left the tests relatively untouched for now, but added a check for the has_secure_password validation.

This lab could use a major overhaul soon, but I'm not sure how pressing that is at the moment.
